# This file lists the dependencies needed to build and test all of libexactreal.
# # Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: libexactreal-build
channels:
  - conda-forge
  - defaults
dependencies:
  - automake
  - benchmark
  - boost-cpp==1.74.0
  - coreutils
  - cxx-compiler
  - libeantic>=1.0.2,<2
  - arb>=2.21,<2.22
  - gmp>6,<7
  - libtool
  - make
  # valgrind is only needed for make check-valgrind
  # - valgrind
